services:
  mysql:
    container_name: psychosolution
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psychosolution
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mysql_data:
  rabbitmq_data: