spring:
  application:
    name: psychosolution

  datasource:
    url: jdbc:mysql://localhost:3305/psychosolution   #Ajustem apenas a porta conforme o necessario
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret