CREATE TABLE pacientes (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
idade INT,
telefone VARCHAR(20),
email VARCHAR(100),
senha VARCHAR(255) NOT NULL,
data_nascimento DATE,
data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);