CREATE TABLE pacientes (
id BINARY(16) PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
idade INT,
telefone VARCHAR(20),
email VARCHAR(100) NOT NULL,
senha VARCHAR(255) NOT NULL,
data_nascimento DATE,
data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);